=== federicogaleasso/Scuola/Galeasso4C/TPSIT/4C_Galeasso_xmlFilm/catalogo.dtd
<!ELEMENT catalogo (film*)>

<!ELEMENT film (titolo, generi, attori, registi, originale, formato, anno, voto?)>
<!ATTLIST film id ID #REQUIRED>

<!ELEMENT titolo (#PCDATA)>

<!ELEMENT registi (regista+)>
<!ELEMENT regista EMPTY>
<!ATTLIST regista nome CDATA #REQUIRED>

<!ELEMENT generi (genere+)>
<!ELEMENT genere EMPTY>
<!ATTLIST genere value CDATA #REQUIRED> 

<!ELEMENT attori (attore*)>
<!ELEMENT attore EMPTY>
<!ATTLIST attore nome CDATA #REQUIRED>

<!ELEMENT formato EMPTY>
<!ATTLIST formato value (VHS | DVD) #REQUIRED>

<!ELEMENT anno EMPTY>
<!ATTLIST anno value CDATA #REQUIRED>

<!ELEMENT originale EMPTY>
<!ATTLIST originale value (si | no) "si">

<!ELEMENT voto EMPTY>
<!ATTLIST voto value (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10) #REQUIRED>

=== federicogaleasso/Scuola/Galeasso4C/TPSIT/4C_Galeasso_xmlFilm/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">
<catalogo>
    <!--1-->
    <film id="l101">
        <titolo>Arizona Junior</titolo>
        <generi>
            <genere value="commedia"/>
        </generi>
        <attori>
            <attore nome="Nicolas Cage"/>
        </attori>
        <registi>
            <regista nome="Ethan Coen"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1987"/>
        <voto value="8"/>
    </film>
    <!--2-->
    <film id="l102">
        <titolo>Lo spaccone</titolo>
        <generi>
            <genere value="romantico"/>
        </generi>
        <attori>
            <attore nome="Paul Newman"/>
        </attori>
        <registi>
            <regista nome="Robert Rossen"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1961"/>
        <voto value="6"/>
    </film>
    <!--3-->
    <film id="l103">
        <titolo>La finestra sul cortile</titolo>
        <generi>
            <genere value="thriller"/>
        </generi>
        <attori>
            <attore nome="James Stewart"/>
        </attori>
        <registi>
            <regista nome="Alfred Hitchcock"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1954"/>
        <voto value="7"/>
    </film>
    <!--4-->
    <film id="l104">
        <titolo>La regola del gioco</titolo>
        <generi>
            <genere value="commedia"/>
        </generi>
        <attori>
            <attore nome="Marcel Dalio"/>
        </attori>
        <registi>
            <regista nome="Jean Renoir"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1939"/>
        <voto value="5"/>
    </film>
    <!--5-->
    <film id="l105">
        <titolo>Qualcuno vol√≤ sul nido del cuculo</titolo>
        <generi>
            <genere value=""/>
        </generi>
        <attori>
            <attore nome="Jack Nicholson"/>
        </attori>
        <registi>
            <regista nome="Milos Forman"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1975"/>
        <voto value="9"/>
    </film>
    <!--6-->
    <film id="l106">
        <titolo>Un uomo per tutte le stagioni</titolo>
        <generi>
            <genere value="storico"/>
        </generi>
        <attori>
            <attore nome="Paul Scofield"/>
        </attori>
        <registi>
            <regista nome="Fred Zinnemann"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1966"/>
        <voto value="3"/>
    </film>
    <!--7-->
    <film id="l107">
        <titolo>Un lupo mannaro americano a londra</titolo>
        <generi>
            <genere value="horror"/>
        </generi>
        <attori>
            <attore nome="David Naughton"/>
        </attori>
        <registi>
            <regista nome="John Landis"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1981"/>
        <voto value="6"/>
    </film>
    <!--8-->
    <film id="l108">
        <titolo>L'albero degli zoccoli</titolo>
        <generi>
            <genere value="drammatico"/>
        </generi>
        <attori>
            <attore nome="Omar Brignoli"/>
        </attori>
        <registi>
            <regista nome="Ermanno Olmi"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1981"/>
        <voto value="5"/>
    </film>
    <!--9-->
    <film id="l109">
        <titolo>L'infernale Quinlan</titolo>
        <generi>
            <genere value="noir"/>
        </generi>
        <attori>
            <attore nome="Janet Leigh"/>
        </attori>
        <registi>
            <regista nome="Orson Welles"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="1958"/>
        <voto value="10"/>
    </film>
    <!--10-->
    <film id="l110">
        <titolo>Befor Sunset-Prima del tramonto</titolo>
        <generi>
            <genere value="romantico"/>
        </generi>
        <attori>
            <attore nome="Ethan Hawke"/>
        </attori>
        <registi>
            <regista nome="Richard Linklater"/>
        </registi>
        <originale/>
        <formato value="DVD"/>
        <anno value="2004"/>
        <voto value="9"/>
    </film>
</catalogo>
